import json
import os
from ...brain import ask_groq

class ArchitectAgent:
    def __init__(self):
        registry_path = os.path.join(os.path.dirname(__file__), 'data/command_registry.json')
        try:
            with open(registry_path, 'r') as f:
                self.command_registry = f.read()
        except FileNotFoundError:
            print(f"Warning: Command registry not found at {registry_path}. Using empty registry.")
            self.command_registry = "{}"

        self.base_system_role = """You are an expert System Architect.
        
        CRITICAL RULE: You MUST output your response as a valid JSON object. 
        Do not include any conversational text outside of the JSON.
        
        Your job is to analyze the user's prompt, determine the best tech stack, and create an execution plan.
        
        COMMAND KNOWLEDGE BASE:
        You must reference the following JSON registry to find the exact, modern commands and packages to use for the user's requested stack. 
        Do NOT rely on your own training data for CLI commands; treat this registry as the absolute source of truth:
        
        {REGISTRY_DATA}
        
        Use this EXACT JSON schema:
        {
            "domain": "The inferred domain (e.g., 'MERN Web App', 'FastAPI Microservice', 'React SPA').",
            "features": [
                "A list of the core functional features.",
                "Example: 'JWT Authentication', 'Real-time WebSocket Chat', 'AI-driven Claim Detection'"
            ],
            "techStack": ["List", "of", "technologies"],
            "setupCommands": [
                "A list of terminal commands strictly adhering to the COMMAND KNOWLEDGE BASE above."
            ],
            "customStructure": {
                "description": "A JSON representation of the folders/files to add ON TOP OF the scaffolded base. Do NOT include files generated by the setupCommands.",
                "tree": {
                     "src": { "features": {}, "middlewares": {} }
                }
            },
            "diagram": "A raw string containing ONLY valid Mermaid.js flowchart code. CRITICAL: You MUST use 'graph TD' (Top-Down layout)."
        }"""

    def execute(self, payload: dict) -> str:
        prompt = payload.get("prompt", "")
        action = payload.get("action", "init")
        history = payload.get("history", [])
        mode = payload.get("mode", "industry") 

        mode_context = ""
        if mode == "industry":
            mode_context = "MODE: Industry-Based. You MUST focus on enterprise-grade architecture, high scalability, robust security, deployment pipelines, and production-ready industry best practices."
        else:
            mode_context = "MODE: Project-Based. You MUST focus on straightforward, easy-to-implement modern architecture. Focus on the core requirements and rapid development. Do NOT over-engineer."

        injected_role = self.base_system_role.replace("{REGISTRY_DATA}", self.command_registry)
        system_role = f"{injected_role}\n\n{mode_context}"

        if action == "init":
            full_prompt = f"Design a system architecture and execution plan for the following request: {prompt}"
            return ask_groq(full_prompt, system_role=system_role, model="llama-3.3-70b-versatile", history=history)
            
        elif action == "analyze":
            project_tree = payload.get("project_tree", "No tree provided.")
            full_prompt = f"Review this project structure against the Knowledge Base for anti-patterns and suggest refactoring:\n\n{project_tree}"
            return ask_groq(full_prompt, system_role=system_role, model="llama-3.3-70b-versatile", history=history)

        else:
            return "Error: Unknown action for ArchitectAgent."